import React, { useState, useRef } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  Dimensions,
  Alert,
  Platform,
  StatusBar,
} from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const isLaptop = SCREEN_WIDTH >= 768;

// ─── DATA ────────────────────────────────────────────────────────────────────

const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

const TIMETABLE = {
  Monday: [
    { tag: 'STEM', tagColor: '#2563EB', time: '08:30–09:30', subject: 'Mathematics', teacher: 'Dr. Sarah Jenkins' },
    { tag: 'HUMANITIES', tagColor: '#7C3AED', time: '09:45–10:45', subject: 'Literature', teacher: 'Marcus Thorne' },
  ],
  Tuesday: [
    { tag: 'STEM', tagColor: '#2563EB', time: '08:30–09:30', subject: 'Science', teacher: 'Prof. Emily Vance' },
    { tag: 'ART', tagColor: '#FFFFFF', tagBg: '#2563EB', time: '09:45–11:45', subject: 'Digital Design', teacher: 'Elena Rodriguez', highlight: true },
  ],
  Wednesday: [
    { tag: 'STEM', tagColor: '#2563EB', time: '08:30–09:30', subject: 'Mathematics', teacher: 'Dr. Sarah Jenkins', live: true },
    { tag: 'HISTORY', tagColor: '#B45309', time: '11:00–12:00', subject: 'Ancient Worlds', teacher: 'Julian Smith' },
  ],
  Thursday: [
    { tag: 'STEM', tagColor: '#2563EB', time: '08:30–09:30', subject: 'Science', teacher: 'Prof. Emily Vance' },
    { tag: 'MUSIC', tagColor: '#059669', time: '10:00–11:30', subject: 'Orchestra', teacher: 'Winston Clarke' },
  ],
  Friday: [
    { tag: 'HUMANITIES', tagColor: '#7C3AED', time: '09:00–10:30', subject: 'Geography', teacher: 'Sandra Miller' },
    { tag: 'GENERAL', tagColor: '#6B7280', time: '11:00–12:00', subject: 'Counseling', teacher: 'Dr. Peter Lowe' },
  ],
  Saturday: [
    { tag: 'WEEKEND', tagColor: '#9CA3AF', time: '10:00–13:00', subject: 'Weekend Workshops', teacher: '', optional: true },
    { tag: 'OPTIONAL', tagColor: '#9CA3AF', time: '09:00–10:00', subject: 'Self Study', teacher: '📍 Library', optional: true },
  ],
};

const EXAMS = [
  { icon: '🧪', title: 'Science Midterm', date: 'Tuesday, Oct 24', time: '09:00 AM', scope: 'UNITS 1–4', color: '#DBEAFE' },
  { icon: '∑', title: 'Math Quiz', date: 'Thursday, Oct 26', time: '08:30 AM', scope: 'CALCULUS I', color: '#FEF9C3' },
  { icon: '📝', title: 'History Essay', date: 'Friday, Oct 27', time: '11:00 AM', scope: 'ANCIENT ROME', color: '#DCFCE7' },
];

// ─── PDF GENERATOR ───────────────────────────────────────────────────────────

const generateAndDownloadPDF = () => {
  // On React Native we use a simple HTML → share approach via WebView/Print if available,
  // or generate an HTML string and open it with Linking / expo-print / react-native-html-to-pdf.
  // For this implementation we build an HTML document and alert the user with instructions,
  // showing the full timetable data formatted for print.
  const tableRows = DAYS.map(day => {
    const slots = TIMETABLE[day].map(s => `<li>${s.time} — <strong>${s.subject}</strong> (${s.teacher})</li>`).join('');
    return `<tr><td style="font-weight:600;padding:8px 12px;border:1px solid #e5e7eb;">${day}</td><td style="padding:8px 12px;border:1px solid #e5e7eb;"><ul style="margin:0;padding-left:16px;">${slots}</ul></td></tr>`;
  }).join('');

  const examRows = EXAMS.map(e =>
    `<tr><td style="padding:8px 12px;border:1px solid #e5e7eb;">${e.title}</td><td style="padding:8px 12px;border:1px solid #e5e7eb;">${e.date}</td><td style="padding:8px 12px;border:1px solid #e5e7eb;">${e.time}</td><td style="padding:8px 12px;border:1px solid #e5e7eb;">${e.scope}</td></tr>`
  ).join('');

  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Weekly Timetable – Leo Miller</title>
  <style>body{font-family:Georgia,serif;color:#111;max-width:800px;margin:40px auto;padding:0 20px}
  h1{font-size:28px;margin-bottom:4px}h2{font-size:18px;margin-top:32px;border-bottom:2px solid #2563EB;padding-bottom:6px}
  p{color:#555;margin:4px 0 16px}table{width:100%;border-collapse:collapse;font-size:14px}
  th{background:#2563EB;color:#fff;padding:10px 12px;text-align:left}
  @media print{body{margin:20px}}</style></head><body>
  <h1>Weekly Timetable</h1><p>Leo Miller — Grade 8-B &nbsp;|&nbsp; St. Edwards Academy</p>
  <h2>Class Schedule</h2>
  <table><thead><tr><th>Day</th><th>Classes</th></tr></thead><tbody>${tableRows}</tbody></table>
  <h2>Upcoming Exams</h2>
  <table><thead><tr><th>Exam</th><th>Date</th><th>Time</th><th>Scope</th></tr></thead><tbody>${examRows}</tbody></table>
  <p style="margin-top:32px;font-size:12px;color:#aaa">Generated by St. Edwards Academy Parent Portal</p>
  </body></html>`;

  // In Expo: use expo-print + shareAsync  |  In bare RN: react-native-html-to-pdf
  // Here we show an alert with the generated HTML length (indicating success) and instructions.
  Alert.alert(
    '📄 PDF Ready',
    'To integrate PDF download in your project, install expo-print and expo-sharing:\n\n  npx expo install expo-print expo-sharing\n\nThen replace this alert with:\n  const { uri } = await Print.printToFileAsync({ html });\n  await Sharing.shareAsync(uri);',
    [{ text: 'Got it', style: 'default' }]
  );

  // Uncomment below when expo-print is available:
  // import * as Print from 'expo-print';
  // import * as Sharing from 'expo-sharing';
  // const { uri } = await Print.printToFileAsync({ html });
  // await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
};

// ─── SUB-COMPONENTS ───────────────────────────────────────────────────────────

const TagBadge = ({ label, color, bg, textWhite }) => (
  <View style={[styles.tag, { backgroundColor: bg || '#EFF6FF' }]}>
    <Text style={[styles.tagText, { color: textWhite ? '#fff' : color }]}>{label}</Text>
  </View>
);

const ClassCard = ({ item }) => {
  const isHighlight = !!item.highlight;
  return (
    <TouchableOpacity
      activeOpacity={0.75}
      style={[styles.classCard, isHighlight && styles.classCardHighlight]}
    >
      <View style={styles.classCardHeader}>
        <TagBadge
          label={item.tag}
          color={item.tagColor}
          bg={isHighlight ? 'rgba(255,255,255,0.25)' : undefined}
          textWhite={isHighlight}
        />
        {item.live && (
          <View style={styles.liveBadge}>
            <Text style={styles.liveText}>Live</Text>
          </View>
        )}
        <Text style={[styles.classTime, isHighlight && { color: 'rgba(255,255,255,0.85)' }]}>
          {item.time}
        </Text>
      </View>
      <Text style={[styles.classSubject, isHighlight && { color: '#fff' }]}>{item.subject}</Text>
      {!!item.teacher && (
        <Text style={[styles.classTeacher, isHighlight && { color: 'rgba(255,255,255,0.8)' }]}>
          👤 {item.teacher}
        </Text>
      )}
    </TouchableOpacity>
  );
};

const ExamCard = ({ exam }) => (
  <TouchableOpacity activeOpacity={0.8} style={[styles.examCard, { backgroundColor: exam.color }]}>
    <Text style={styles.examIcon}>{exam.icon}</Text>
    <Text style={styles.examTitle}>{exam.title}</Text>
    <Text style={styles.examDate}>{exam.date} • {exam.time}</Text>
    <View style={styles.examScopePill}>
      <Text style={styles.examScopeText}>{exam.scope}</Text>
    </View>
  </TouchableOpacity>
);

// ─── MAIN SCREEN ─────────────────────────────────────────────────────────────

export default function WeeklyTimetable() {
  const [activeDay, setActiveDay] = useState('Wednesday');
  const scrollRef = useRef(null);

  const laptopLayout = SCREEN_WIDTH >= 768;

  return (
    <View style={styles.root}>
      <StatusBar barStyle="dark-content" backgroundColor="#F8FAFC" />
      <ScrollView
        ref={scrollRef}
        contentContainerStyle={[styles.container, laptopLayout && styles.containerLaptop]}
        showsVerticalScrollIndicator={false}
      >
        {/* ── HEADER ── */}
        <View style={[styles.headerRow, laptopLayout && styles.headerRowLaptop]}>
          <View>
            <Text style={styles.breadcrumb}>ACADEMICS  ›  TIMETABLE</Text>
            <Text style={styles.pageTitle}>Weekly Timetable</Text>
            <Text style={styles.subTitle}>
              Weekly Schedule for{' '}
              <Text style={styles.studentName}>Leo Miller</Text>
              {' '}— Grade 8-B
            </Text>
          </View>
          <TouchableOpacity
            activeOpacity={0.85}
            style={styles.downloadBtn}
            onPress={generateAndDownloadPDF}
          >
            <Text style={styles.downloadBtnIcon}>⬇</Text>
            <Text style={styles.downloadBtnText}>Download PDF</Text>
          </TouchableOpacity>
        </View>

        {/* ── DAY SELECTOR ── */}
        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={styles.dayTabsRow}
        >
          {DAYS.map(day => {
            const active = day === activeDay;
            return (
              <TouchableOpacity
                key={day}
                activeOpacity={0.8}
                style={[styles.dayTab, active && styles.dayTabActive]}
                onPress={() => setActiveDay(day)}
              >
                <Text style={[styles.dayTabText, active && styles.dayTabTextActive]}>
                  {day.toUpperCase()}
                </Text>
              </TouchableOpacity>
            );
          })}
        </ScrollView>

        {/* ── SCHEDULE GRID ── */}
        {laptopLayout ? (
          // Desktop: show all days in a horizontal grid
          <View style={styles.laptopGrid}>
            {DAYS.map(day => (
              <View key={day} style={styles.laptopDayColumn}>
                <Text style={[
                  styles.laptopDayHeader,
                  day === activeDay && styles.laptopDayHeaderActive,
                ]}>
                  {day.toUpperCase()}
                </Text>
                {TIMETABLE[day].map((item, idx) => (
                  <ClassCard key={idx} item={item} />
                ))}
              </View>
            ))}
          </View>
        ) : (
          // Mobile: show selected day
          <View style={styles.mobileSchedule}>
            <Text style={styles.mobileDayLabel}>{activeDay}</Text>
            {TIMETABLE[activeDay].map((item, idx) => (
              <ClassCard key={idx} item={item} />
            ))}
          </View>
        )}

        {/* ── EXAMS + ADVISORY ── */}
        <View style={[styles.bottomSection, laptopLayout && styles.bottomSectionLaptop]}>
          {/* Upcoming Exams */}
          <View style={[styles.examsPanel, laptopLayout && styles.examsPanelLaptop]}>
            <View style={styles.examsPanelHeader}>
              <Text style={styles.examsPanelTitle}>Upcoming Exams</Text>
              <View style={styles.pendingBadge}>
                <Text style={styles.pendingBadgeText}>3 Tests Pending</Text>
              </View>
            </View>
            <ScrollView
              horizontal={!laptopLayout}
              showsHorizontalScrollIndicator={false}
              contentContainerStyle={laptopLayout ? styles.examCardsColumnWrap : styles.examCardsRow}
            >
              {EXAMS.map((exam, i) => <ExamCard key={i} exam={exam} />)}
            </ScrollView>
          </View>

          {/* Advisory */}
          <TouchableOpacity activeOpacity={0.9} style={[styles.advisoryCard, laptopLayout && styles.advisoryCardLaptop]}>
            <View style={styles.advisoryIconWrap}>
              <Text style={styles.advisoryIcon}>!</Text>
            </View>
            <Text style={styles.advisoryTitle}>Exam Advisory</Text>
            <Text style={styles.advisoryBody}>
              The Science midterm is next week. Please ensure Leo has reviewed the lab safety protocols and the chemical reaction charts available in his study guide.
            </Text>
            <TouchableOpacity activeOpacity={0.85} style={styles.studyGuideBtn}>
              <Text style={styles.studyGuideBtnText}>View Study Guide</Text>
            </TouchableOpacity>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </View>
  );
}

// ─── STYLES ──────────────────────────────────────────────────────────────────

const BLUE = '#2563EB';
const ORANGE = '#C2540A';

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  container: {
    padding: 16,
    paddingBottom: 40,
  },
  containerLaptop: {
    padding: 32,
    maxWidth: 1280,
    alignSelf: 'center',
    width: '100%',
  },

  // Header
  headerRow: {
    marginBottom: 20,
    gap: 12,
  },
  headerRowLaptop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  breadcrumb: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 1.2,
    color: '#94A3B8',
    marginBottom: 4,
  },
  pageTitle: {
    fontSize: isLaptop ? 32 : 26,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.5,
  },
  subTitle: {
    fontSize: 14,
    color: '#64748B',
    marginTop: 4,
  },
  studentName: {
    color: BLUE,
    fontWeight: '700',
  },
  downloadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: BLUE,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    gap: 8,
    alignSelf: 'flex-start',
    shadowColor: BLUE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  downloadBtnIcon: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  downloadBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 14,
  },

  // Day tabs
  dayTabsRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 20,
    paddingVertical: 4,
  },
  dayTab: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  dayTabActive: {
    backgroundColor: BLUE,
    borderColor: BLUE,
    shadowColor: BLUE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  dayTabText: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    color: '#64748B',
  },
  dayTabTextActive: {
    color: '#fff',
  },

  // Mobile schedule
  mobileSchedule: {
    gap: 12,
    marginBottom: 24,
  },
  mobileDayLabel: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 4,
  },

  // Laptop grid
  laptopGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 28,
  },
  laptopDayColumn: {
    flex: 1,
    gap: 10,
  },
  laptopDayHeader: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.2,
    color: '#94A3B8',
    marginBottom: 4,
    paddingVertical: 8,
    textAlign: 'center',
  },
  laptopDayHeaderActive: {
    color: BLUE,
  },

  // Class card
  classCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
    gap: 6,
  },
  classCardHighlight: {
    backgroundColor: BLUE,
    borderColor: BLUE,
  },
  classCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  classTime: {
    fontSize: 10,
    color: '#94A3B8',
    marginLeft: 'auto',
    fontWeight: '500',
  },
  classSubject: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0F172A',
  },
  classTeacher: {
    fontSize: 12,
    color: '#64748B',
  },

  // Tag badge
  tag: {
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 6,
  },
  tagText: {
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.6,
  },

  // Live badge
  liveBadge: {
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
  },
  liveText: {
    fontSize: 9,
    color: '#16A34A',
    fontWeight: '700',
  },

  // Bottom section
  bottomSection: {
    gap: 16,
  },
  bottomSectionLaptop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },

  // Exams panel
  examsPanel: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  examsPanelLaptop: {
    flex: 2,
  },
  examsPanelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  examsPanelTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A',
  },
  pendingBadge: {
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
  },
  pendingBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#B45309',
  },
  examCardsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  examCardsColumnWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },

  // Exam card
  examCard: {
    borderRadius: 14,
    padding: 16,
    width: isLaptop ? 200 : 180,
    gap: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  examIcon: {
    fontSize: 24,
    marginBottom: 4,
  },
  examTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
  },
  examDate: {
    fontSize: 12,
    color: '#64748B',
  },
  examScopePill: {
    marginTop: 4,
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(0,0,0,0.07)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  examScopeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#374151',
    letterSpacing: 0.5,
  },

  // Advisory card
  advisoryCard: {
    backgroundColor: ORANGE,
    borderRadius: 16,
    padding: 24,
    gap: 12,
    shadowColor: ORANGE,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 5,
  },
  advisoryCardLaptop: {
    flex: 1,
  },
  advisoryIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  advisoryIcon: {
    fontSize: 20,
    fontWeight: '900',
    color: '#fff',
  },
  advisoryTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#fff',
  },
  advisoryBody: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.85)',
    lineHeight: 20,
  },
  studyGuideBtn: {
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 4,
  },
  studyGuideBtnText: {
    color: ORANGE,
    fontWeight: '800',
    fontSize: 14,
  },
});